using System.Collections.Generic;

namespace DnDDM.Classes
{
    public class StandardItemLists
    {
        public StandardItemLists() 
        {
            armor.Sort((x, y) => x.Description.CompareTo(y.Description));
            weapons.Sort((x, y) => x.Description.CompareTo(y.Description));
            goods.Sort((x, y) => x.Description.CompareTo(y.Description));
            trinkets.Sort((x, y) => x.Description.CompareTo(y.Description));
            art.Sort((x, y) => x.Description.CompareTo(y.Description));
            gems.Sort((x, y) => x.ItemName.CompareTo(y.ItemName));
        }

        public List<StandardItem> armor = new List<StandardItem>()
        {
            new StandardItem("Padded", "5 gp", "11 + Dex Modifier", "-", "Disadvantage", "8 lbs", DefaultValues.lightAmor),
            new StandardItem("Leather", "10 gp", "11 + Dex Modifier", "-", "-", "10 lbs", DefaultValues.lightAmor),
            new StandardItem("Studded Leather", "45 gp", "12 + Dex Modifier", "-", "-", "13 lbs", DefaultValues.lightAmor),
            new StandardItem("Hide", "10 gp", "12 + Dex Modifier (Max 2)", "-", "-", "12 lbs", DefaultValues.mediumAmor),
            new StandardItem("Chain Shirt", "50 gp", "13 + Dex Modifier (Max 2)", "-", "-", "20 lbs", DefaultValues.mediumAmor),
            new StandardItem("Scale Mail", "50 gp", "14 + Dex Modifier (Max 2)", "-", "Disadvantage", "45 lbs", DefaultValues.mediumAmor),
            new StandardItem("Breastplate", "400 gp", "14 + Dex Modifier (Max 2)", "-", "-", "20 lbs", DefaultValues.mediumAmor),
            new StandardItem("Half Plate", "750 gp", "15 + Dex Modifier (Max 2)", "-", "Disadvantage", "40 lbs", DefaultValues.mediumAmor),
            new StandardItem("Ring Mail", "30 gp", "14", "-", "Disadvantage", "40 lbs", DefaultValues.heavyAmor),
            new StandardItem("Chain Mail", "75 gp", "16", "13", "Disadvantage", "55 lbs", DefaultValues.heavyAmor),
            new StandardItem("Splint", "200 gp", "17", "15", "Disadvantage", "60 lbs", DefaultValues.heavyAmor),
            new StandardItem("Plate", "1,500 gp", "18", "15", "Disadvantage", "65 lbs", DefaultValues.heavyAmor),
            new StandardItem("Shield", "10 gp", "+2", "-", "-", "6 lbs", DefaultValues.shields)
        };

        public List<StandardItem> weapons = new List<StandardItem>()
        {
            new StandardItem("Club", "1 sp", "1d4 bludgeoning", "2 lbs", "Light", DefaultValues.simpleMelee),
            new StandardItem("Dagger", "2 gp", "1d4 piercing",  "1 lbs", "Finesse, Light, Thrown (range 20/60)", DefaultValues.simpleMelee),
            new StandardItem("Greatclub", "2 sp", "1d8 bludgeoning", "10 lbs", "Two-handed", DefaultValues.simpleMelee),
            new StandardItem("Handaxe", "5 gp", "1d6 slashing", "2 lbs", "Light, Thrown (range 20/60)", DefaultValues.simpleMelee),
            new StandardItem("Javelin", "5 sp", "1d6 piercing", "2 lbs", "Thrown (range 30/120)", DefaultValues.simpleMelee),
            new StandardItem("Light Hammer", "2 gp", "1d4 bludgeoning", "2 lbs", "Light, Thrown (range 20/60)", DefaultValues.simpleMelee),
            new StandardItem("Mace", "5 gp", "1d6 bludgeoning", "4 lbs",  "-", DefaultValues.simpleMelee),
            new StandardItem("Quarterstaff", "2 sp", "1d6 bludgeoning", "4 lbs", "Versatile (1d8)", DefaultValues.simpleMelee),
            new StandardItem("Sickle", "1 gp", "1d4 slashing", "2 lbs", "Light", DefaultValues.simpleMelee),
            new StandardItem("Spear", "1 gp", "1d6 piercing", "3 lbs", "Thrown (range 20/60), Versatile (1d8)", DefaultValues.simpleMelee),
            new StandardItem("Crossbow, Light", "25 gp", "1d8 piercing", "5 lbs", "Ammunition (range 80/320), Loading, Two-handed", DefaultValues.simpleRanged),
            new StandardItem("Dart", "5 cp", "1d4 piercing", "1/4 lbs", "Finesse, Thrown (range 20/60)", DefaultValues.simpleRanged),
            new StandardItem("Shortbow", "25 gp", "1d6 piercing", "2 lbs", "Ammunition (range 80/320), Two-handed", DefaultValues.simpleRanged),
            new StandardItem("Sling", "1 sp", "1d4 bludgeoning", "-", "Ammunition (range 30/120)", DefaultValues.simpleRanged),
            new StandardItem("Battleaxe", "10 gp", "1d8 slashing", "4 lbs", "Versatile (1d10)", DefaultValues.martialMelee),
            new StandardItem("Flail", "10 gp", "1d8 bludgeoning", "2 lbs", "-", DefaultValues.martialMelee),
            new StandardItem("Glaive", "20 gp", "1d10 slashing", "6 lbs", "Heavy, Reach, Two-handed", DefaultValues.martialMelee),
            new StandardItem("Greataxe", "30 gp", "1d12 slashing", "7 lbs", "Heavy, Two-handed", DefaultValues.martialMelee),
            new StandardItem("Greatsword", "50 gp", "2d6 slashing", "6 lbs", "Heavy, Two-handed", DefaultValues.martialMelee),
            new StandardItem("Halberd", "20 gp",    "1d10 slashing", "6 lbs", "Heavy, Reach, Two-handed", DefaultValues.martialMelee),
            new StandardItem("Lance", "10 gp", "1d12 piercing", "6 lbs", "Reach, Special", DefaultValues.martialMelee),
            new StandardItem("Longsword", "15 gp", "1d8 slashing", "3 lbs", "Versatile (1d10)", DefaultValues.martialMelee),
            new StandardItem("Maul", "10 gp", "2d6 bludgeoning", "10 lbs", "Heavy, Two-handed", DefaultValues.martialMelee),
            new StandardItem("Morningstar", "15 gp", "1d8 piercing", "4 lbs", "-", DefaultValues.martialMelee),
            new StandardItem("Pike", "5 gp", "1d10 piercing", "18 lbs", "Heavy, Reach, Two-handed", DefaultValues.martialMelee),
            new StandardItem("Rapier", "25 gp", "1d8 piercing", "2 lbs", "Finesse", DefaultValues.martialMelee),
            new StandardItem("Scimitar", "25 gp", "1d6 slashing", "3 lbs", "Finesse, Light", DefaultValues.martialMelee),
            new StandardItem("Shortsword", "10 gp", "1d6 piercing", "2 lbs", "Finesse, Light", DefaultValues.martialMelee),
            new StandardItem("Trident", "5 gp", "1d6 piercing", "4 lbs", "Thrown (range 20/60), Versatile (1d8)", DefaultValues.martialMelee),
            new StandardItem("War Pick", "5 gp", "1d8 piercing", "2 lbs", "-", DefaultValues.martialMelee),
            new StandardItem("Warhammer", "15 gp", "1d8 bludgeoning", "2 lbs", "Versatile (1d10)", DefaultValues.martialMelee),
            new StandardItem("Whip", "2 gp", "1d4 slashing", "3 lbs", "Finesse, Reach", DefaultValues.martialMelee),
            new StandardItem("Blowgun", "10 gp", "1 piercing", "1 lbs", "Ammunition (range 25/100), Loading", DefaultValues.martialRanged),
            new StandardItem("Crossbow, Hand", "75 gp", "1d6 piercing", "3 lbs", "Ammunition (range 30/120), Light, Loading", DefaultValues.martialRanged),
            new StandardItem("Crossbow, Heavy", "50 gp", "1d10 piercing", "18 lbs", "Ammunition (range 100/400), Heavy, Loading, Two-handed", DefaultValues.martialRanged),
            new StandardItem("Longbow", "50 gp", "1d8 piercing", "2 lbs", "Ammunition (range 150/600), Heavy, Two-handed", DefaultValues.martialRanged),
            new StandardItem("Net", "1 gp", "-", "3 lbs", "Special, Thrown (range 5/15)", DefaultValues.martialRanged)
        };

        public List<StandardItem> goods = new List<StandardItem>()
        {
            new StandardItem("Abacus", "2 gp",  "2 lb", DefaultValues.Good),
            new StandardItem("Acid (vial)", "25 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Alchemist's fire (flask)", "50 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Antitoxin (vial)", "50 gp", "-", DefaultValues.Good),
            new StandardItem("Backpack", "2 gp", "5 lbs", DefaultValues.Good),
            new StandardItem("Ball bearings (bag of 1,000)", "1 gp", "2 lbs", DefaultValues.Good),
            new StandardItem("Barrel",  "2 gp", "70 lbs", DefaultValues.Good),
            new StandardItem("Basket",  "4 sp", "2 lbs", DefaultValues.Good),
            new StandardItem("Bedroll", "1 gp", "7 lbs", DefaultValues.Good),
            new StandardItem("Bell",    "1 gp", "-", DefaultValues.Good),
            new StandardItem("Blanket", "5 sp", "3 lbs", DefaultValues.Good),
            new StandardItem("Block and tackle", "1 gp", "5 lbs", DefaultValues.Good),
            new StandardItem("Book", "25 gp", "5 lbs", DefaultValues.Good),
            new StandardItem("Bottle, glass",   "2 gp", "2 lbs", DefaultValues.Good),
            new StandardItem("Bucket",  "5 cp", "2 lbs", DefaultValues.Good),
            new StandardItem("Caltrops (bag of 20)", "1 gp", "2 lbs", DefaultValues.Good),
            new StandardItem("Candle",  "1 cp", "-", DefaultValues.Good),
            new StandardItem("Case, crossbow bolt", "1 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Case, map or scroll", "1 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Chain (10 feet)", "5 gp", "10 lbs", DefaultValues.Good),
            new StandardItem("Chalk (1 piece)", "1 cp", "-", DefaultValues.Good),
            new StandardItem("Chest", "5 gp", "25 lbs", DefaultValues.Good),
            new StandardItem("Climber's kit", "25 gp", "12 lbs", DefaultValues.Good),
            new StandardItem("Clothes, common", "5 sp", "3 lbs", DefaultValues.Good),
            new StandardItem("Clothes, costume", "5 gp", "4 lbs", DefaultValues.Good),
            new StandardItem("Clothes, fine", "15 gp", "6 lbs", DefaultValues.Good),
            new StandardItem("Clothes, traveler's", "2 gp", "4 lbs", DefaultValues.Good),
            new StandardItem("Component pouch", "25 gp", "2 lbs", DefaultValues.Good),
            new StandardItem("Crowbar", "2 gp", "5 lbs", DefaultValues.Good),
            new StandardItem("Fishing tackle", "1 gp",  "4 lbs", DefaultValues.Good),
            new StandardItem("Flask or tankard", "2 cp", "1 lb", DefaultValues.Good),
            new StandardItem("Grappling hook", "2 gp",  "4 lbs", DefaultValues.Good),
            new StandardItem("Hammer",  "1 gp", "3 lbs", DefaultValues.Good),
            new StandardItem("Hammer, sledge", "2 gp",  "10 lbs", DefaultValues.Good),
            new StandardItem("Healer's kit", "5 gp", "3 lbs", DefaultValues.Good),
            new StandardItem("Holy water (flask)",  "25 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Hourglass", "25 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Hunting trap", "5 gp", "25 lbs", DefaultValues.Good),
            new StandardItem("Ink (1 ounce bottle)", "10 gp", "-", DefaultValues.Good),
            new StandardItem("Ink pen", "2 cp", "-", DefaultValues.Good),
            new StandardItem("Jug or pitcher", "2 cp", "4 lbs", DefaultValues.Good),
            new StandardItem("Ladder (10 foot)", "1 sp", "25 lb", DefaultValues.Good),
            new StandardItem("Lamp", "5 sp", "1 lb", DefaultValues.Good),
            new StandardItem("Lantern, bullseye", "10 gp", "2 lbs", DefaultValues.Good),
            new StandardItem("Lantern, hooded", "5 gp", "2 lbs", DefaultValues.Good),
            new StandardItem("Lock", "10 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Magnifying glass", "100 gp", "-", DefaultValues.Good),
            new StandardItem("Manacles", "2 gp", "6 lbs", DefaultValues.Good),
            new StandardItem("Mess kit", "2 sp", "1 lb", DefaultValues.Good),
            new StandardItem("Mirror, steel", "5 gp", "1/2 lb", DefaultValues.Good),
            new StandardItem("Oil (flask)", "1 sp", "1 lb", DefaultValues.Good),
            new StandardItem("Paper (one sheet)", "2 sp", "-", DefaultValues.Good),
            new StandardItem("Parchment (one sheet)", "1 sp", "-", DefaultValues.Good),
            new StandardItem("Perfume (vial)", "5 gp", "-", DefaultValues.Good),
            new StandardItem("Pick, miner's", "2 gp", "10 lbs", DefaultValues.Good),
            new StandardItem("Piton", "5 cp", "1/4 lb", DefaultValues.Good),
            new StandardItem("Poison, basic (vial)", "100 gp", "-", DefaultValues.Good),
            new StandardItem("Pole (10-foot)", "5 cp", "7 lbs", DefaultValues.Good),
            new StandardItem("Pot, iron", "2 gp", "10 lbs", DefaultValues.Good),
            new StandardItem("Potion of healing", "50 gp", "1/2 lb", DefaultValues.Good),
            new StandardItem("Pouch", "5 sp", "1 lb", DefaultValues.Good),
            new StandardItem("Quiver", "1 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Ram, portable", "4 gp", "35 lbs", DefaultValues.Good),
            new StandardItem("Rations (1 day)", "5 sp", "2 lbs", DefaultValues.Good),
            new StandardItem("Robes", "1 gp", "4 lbs", DefaultValues.Good),
            new StandardItem("Rope, hempen (50 feet)", "1 gp", "10 lbs", DefaultValues.Good),
            new StandardItem("Rope, silk (50 feet)", "10 gp", "5 lbs", DefaultValues.Good),
            new StandardItem("Sack", "1 cp", "1/2 lb", DefaultValues.Good),
            new StandardItem("Scale, merchant's", "5 gp", "3 lbs", DefaultValues.Good),
            new StandardItem("Sealing wax", "5 sp", "-", DefaultValues.Good),
            new StandardItem("Shovel", "2 gp", "5 lbs", DefaultValues.Good),
            new StandardItem("Signal whistle", "5 cp",  "-", DefaultValues.Good),
            new StandardItem("Signet ring"," 5 gp", "-", DefaultValues.Good),
            new StandardItem("Soap", "2 cp", "-", DefaultValues.Good),
            new StandardItem("Spellbook", "50 gp", "3 lbs", DefaultValues.Good),
            new StandardItem("Spikes, iron (10)", "1 gp", "5 lbs", DefaultValues.Good),
            new StandardItem("Spyglass", "1,000 gp", "1 lb", DefaultValues.Good),
            new StandardItem("Tent, two-person", "2 gp", "20 lbs", DefaultValues.Good),
            new StandardItem("Tinderbox", "5 sp", "1 lb", DefaultValues.Good),
            new StandardItem("Torch", "1 cp", "1 lb", DefaultValues.Good),
            new StandardItem("Vial", "1 gp", "-", DefaultValues.Good),
            new StandardItem("Waterskin (full)", "2 sp", "5 lbs", DefaultValues.Good),
            new StandardItem("Whetstone", "1 cp", "1 lb", DefaultValues.Good),
            new StandardItem("Arrows (20)", "1 gp", "1 lb", DefaultValues.ammunition),
            new StandardItem("Blowgun Needles (50)", "1 gp", "1 lb", DefaultValues.ammunition),
            new StandardItem("Crossbow Bolts (20)", "1 gp", "1 1/2 lbs", DefaultValues.ammunition),
            new StandardItem("Sling Bullets (20)", "4 cp", "1 1/2 lbs", DefaultValues.ammunition),
            new StandardItem("Crystal", "10 gp", "1 lb", DefaultValues.arcaneFocus),
            new StandardItem("Orb", "20 gp", "3 lbs", DefaultValues.arcaneFocus),
            new StandardItem("Rod", "10 gp", "2 lb", DefaultValues.arcaneFocus),
            new StandardItem("Staff", "5 gp", "4 lbs", DefaultValues.arcaneFocus),
            new StandardItem("Wand", "10 gp", "1 lb", DefaultValues.arcaneFocus),
            new StandardItem("Sprig of Mistletoe", "1 gp", "-", DefaultValues.druidicFocus),
            new StandardItem("Totem", "1 gp", "-", DefaultValues.druidicFocus),
            new StandardItem("Wooden Staff", "5 gp", "4 lbs", DefaultValues.druidicFocus),
            new StandardItem("Yew Wand", "10 gp", "1 lb", DefaultValues.druidicFocus)
        };

        public List<StandardItem> trinkets = new List<StandardItem>()
        {
            new StandardItem("A mummified goblin hand"),
            new StandardItem("A piece of crystal that faintly glows in the moonlight"),
            new StandardItem("A gold coin minted in an unknown land"),
            new StandardItem("A diary written in a language you don’t know"),
            new StandardItem("A brass ring that never tarnishes"),
            new StandardItem("An old chess piece made from glass"),
            new StandardItem("A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips"),
            new StandardItem("A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it"),
            new StandardItem("A rope necklace from which dangles four mummified elf fingers"),
            new StandardItem("The deed for a parcel of land in a realm unknown to you"),
            new StandardItem("A 1-ounce block made from an unknown material"),
            new StandardItem("A small cloth doll skewered with needles"),
            new StandardItem("A tooth from an unknown beast"),
            new StandardItem("An enormous scale), perhaps from a dragon"),
            new StandardItem("A bright green feather"),
            new StandardItem("An old divination card bearing your likeness"),
            new StandardItem("A glass orb filled with moving smoke"),
            new StandardItem("A 1-pound egg with a bright red shell"),
            new StandardItem("A pipe that blows bubbles"),
            new StandardItem("A glass jar containing a weird bit of flesh floating in pickling fluid"),
            new StandardItem("A tiny gnome-crafted music box that plays a song you dimly remember from your childhood"),
            new StandardItem("A small wooden statuette of a smug halfling"),
            new StandardItem("A brass orb etched with strange runes"),
            new StandardItem("A multicolored stone disk"),
            new StandardItem("A tiny silver icon of a raven"),
            new StandardItem("A bag containing forty-seven humanoid teeth, one of which is rotten"),
            new StandardItem("A shard of obsidian that always feels warm to the touch"),
            new StandardItem("A dragon's bony talon hanging from a plain leather necklace"),
            new StandardItem("A pair of old socks"),
            new StandardItem("A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking"),
            new StandardItem("A silver badge in the shape of a five-pointed star"),
            new StandardItem("A knife that belonged to a relative"),
            new StandardItem("A glass vial filled with nail clippings"),
            new StandardItem("A rectangular metal device with two tiny metal cups on one end that throws sparks when wet"),
            new StandardItem("A white, sequined glove sized for a human"),
            new StandardItem("A vest with one hundred tiny pockets"),
            new StandardItem("A small, weightless stone block"),
            new StandardItem("A tiny sketch portrait of a goblin"),
            new StandardItem("An empty glass vial that smells of perfume when opened"),
            new StandardItem("A gemstone that looks like a lump of coal when examined by anyone but you"),
            new StandardItem("A scrap of cloth from an old banner"),
            new StandardItem("A rank insignia from a lost legionnaire"),
            new StandardItem("A tiny silver bell without a clapper"),
            new StandardItem("A mechanical canary inside a gnome-crafted lamp"),
            new StandardItem("A tiny chest carved to look like it has numerous feet on the bottom"),
            new StandardItem("A dead sprite inside a clear glass bottle"),
            new StandardItem("A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)"),
            new StandardItem("A glass orb filled with water, in which swims a clockwork goldfish"),
            new StandardItem("A silver spoon with an M engraved on the handle"),
            new StandardItem("A whistle made from gold-colored wood"),
            new StandardItem("A dead scarab beetle the size of your hand"),
            new StandardItem("Two toy soldiers, one with a missing head"),
            new StandardItem("A small box filled with different-sized buttons"),
            new StandardItem("A candle that can’t be lit"),
            new StandardItem("A tiny cage with no door"),
            new StandardItem("An old key"),
            new StandardItem("An indecipherable treasure map"),
            new StandardItem("A hilt from a broken sword"),
            new StandardItem("A rabbit’s foot"),
            new StandardItem("A glass eye"),
            new StandardItem("A cameo carved in the likeness of a hideous person"),
            new StandardItem("A silver skull the size of a coin"),
            new StandardItem(" An alabaster mask"),
            new StandardItem("A pyramid of sticky black incense that smells very bad"),
            new StandardItem("A nightcap that, when worn, gives you pleasant dreams"),
            new StandardItem("A single caltrop made from bone"),
            new StandardItem("A gold monocle frame without the lens"),
            new StandardItem("A 1-inch cube, each side painted a different color"),
            new StandardItem("A crystal knob from a door"),
            new StandardItem("A small packet filled with pink dust"),
            new StandardItem("A fragment of a beautiful song, written as musical notes on two pieces of parchment"),
            new StandardItem("A silver teardrop earring made from a real teardrop"),
            new StandardItem("The shell of an egg painted with scenes of human misery in disturbing detail"),
            new StandardItem("A fan that, when unfolded, shows a sleeping cat"),
            new StandardItem("A set of bone pipes"),
            new StandardItem("A four-leaf clover pressed inside a book discussing manners and etiquette"),
            new StandardItem("A sheet of parchment upon which is drawn a complex mechanical contraption"),
            new StandardItem("An ornate scabbard that fits no blade you have found so far"),
            new StandardItem("An invitation to a party where a murder happened"),
            new StandardItem("A bronze pentacle with an etching of a rat's head in its center"),
            new StandardItem("A purple handkerchief embroidered with the name of a powerful archmage"),
            new StandardItem("Half of a floorplan for a temple, castle, or some other structure"),
            new StandardItem("A bit of folded cloth that, when unfolded, turns into a stylish cap"),
            new StandardItem("A receipt of deposit at a bank in a far-flung city"),
            new StandardItem("A diary with seven missing pages"),
            new StandardItem("An empty silver snuffbox bearing an inscription on the surface that says “dreams”"),
            new StandardItem("An iron holy symbol devoted to an unknown god"),
            new StandardItem("A book that tells the story of a legendary hero's rise and fall, with the last chapter missing"),
            new StandardItem("A vial of dragon blood"),
            new StandardItem("An ancient arrow of elven design"),
            new StandardItem("A needle that never bends"),
            new StandardItem("An ornate brooch of dwarven design"),
            new StandardItem("An empty wine bottle bearing a pretty label that says, “The Wizard of Wines Winery, Red Dragon Crush, 331422-W”"),
            new StandardItem("A mosaic tile with a multicolored, glazed surface"),
            new StandardItem("A petrified mouse"),
            new StandardItem("A black pirate flag adorned with a dragon's skull and crossbones"),
            new StandardItem("A tiny mechanical crab or spider that moves about when it’s not being observed"),
            new StandardItem("A glass jar containing lard with a label that reads, Griffon Grease"),
            new StandardItem("A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body"),
            new StandardItem("A metal urn containing the ashes of a hero")
        };

        public List<StandardItem> art = new List<StandardItem>()
        {
            new StandardItem("Silver ewer", DefaultValues.gp25),
            new StandardItem("Carved bone statuette", DefaultValues.gp25),
            new StandardItem("Small gold bracelet", DefaultValues.gp25),
            new StandardItem("Cloth-of-gold vestments", DefaultValues.gp25),
            new StandardItem("Black velvet mask stitched with silver thread", DefaultValues.gp25),
            new StandardItem("Copper chalice with silver filigree", DefaultValues.gp25),
            new StandardItem("Pair of engraved bone dice", DefaultValues.gp25),
            new StandardItem("Small mirror set in a painted wooden frame", DefaultValues.gp25),
            new StandardItem("Embroidered silk handkerchief", DefaultValues.gp25),
            new StandardItem("Gold locket with a painted portrait inside", DefaultValues.gp25),
            new StandardItem("Gold ring set with bloodstones", DefaultValues.gp250),
            new StandardItem("Carved ivory statuette", DefaultValues.gp250),
            new StandardItem("Large gold bracelet", DefaultValues.gp250),
            new StandardItem("Silver necklace with a gemstone pendant", DefaultValues.gp250),
            new StandardItem("Bronze crown", DefaultValues.gp250),
            new StandardItem("Silk robe with gold embroidery", DefaultValues.gp250),
            new StandardItem("Large well-made tapestry", DefaultValues.gp250),
            new StandardItem("Brass mug with jade inlay", DefaultValues.gp250),
            new StandardItem("Box of turquoise animal figurines", DefaultValues.gp250),
            new StandardItem("Gold bird cage with electrum filigree", DefaultValues.gp250),
            new StandardItem("Silver chalice set with moonstones", DefaultValues.gp750),
            new StandardItem("Silver-plated steel longsword with jet set in hilt", DefaultValues.gp750),
            new StandardItem("Carved harp of exotic wood with ivory inlay and zircon gems", DefaultValues.gp750),
            new StandardItem("Small gold idol", DefaultValues.gp750),
            new StandardItem("Gold dragon comb set with red garnets as eyes", DefaultValues.gp750),
            new StandardItem("Bottle stopper cork embossed with gold leaf and set with amethysts", DefaultValues.gp750),
            new StandardItem("Ceremonial electrum dagger with a black pearl in the pommel", DefaultValues.gp750),
            new StandardItem("Silver and gold brooch", DefaultValues.gp750),
            new StandardItem("Obsidian statuette with gold fittings and inlay", DefaultValues.gp750),
            new StandardItem("Painted gold war mask", DefaultValues.gp750),
            new StandardItem("Fine gold chain set with a fire opal", DefaultValues.gp2500),
            new StandardItem("Old masterpiece painting", DefaultValues.gp2500),
            new StandardItem("Embroidered silk and velvet mantle set with numerous moonstones", DefaultValues.gp2500),
            new StandardItem("Platinum bracelet set with a sapphire", DefaultValues.gp2500),
            new StandardItem("Embroidered glove set with jewel chips", DefaultValues.gp2500),
            new StandardItem("Jeweled anklet", DefaultValues.gp2500),
            new StandardItem("Gold music box", DefaultValues.gp2500),
            new StandardItem("Gold circlet set with four aquamarines", DefaultValues.gp2500),
            new StandardItem("Eye patch with a mock eye set in blue sapphire and moonstone", DefaultValues.gp2500),
            new StandardItem("A necklace string of small pink pearls", DefaultValues.gp2500),
            new StandardItem("Jeweled gold crown", DefaultValues.gp7500),
            new StandardItem("Jeweled platinum ring", DefaultValues.gp7500),
            new StandardItem("Small gold statuette set with rubies", DefaultValues.gp7500),
            new StandardItem("Gold cup set with emeralds", DefaultValues.gp7500),
            new StandardItem("Gold jewelry box with platinum filigree", DefaultValues.gp7500),
            new StandardItem("Painted gold child’s sarcophagus", DefaultValues.gp7500),
            new StandardItem("Jade game board with solid gold playing pieces", DefaultValues.gp7500),
            new StandardItem("Bejeweled ivory drinking horn with gold filigree", DefaultValues.gp7500)
        };

        public List<StandardItem> gems = new List<StandardItem>()
        {
            new StandardItem("Azurite", "opaque mottled deep blue", DefaultValues.gp10),
            new StandardItem("Banded Agate", "translucent striped brown, blue, white, or red", DefaultValues.gp10),
            new StandardItem("Blue Quartz", "transparent pale blue", DefaultValues.gp10),
            new StandardItem("Eye Agate", "translucent circles or gray, white, brown, blue, or green", DefaultValues.gp10),
            new StandardItem("Hematite", "opaque gray-black", DefaultValues.gp10),
            new StandardItem("Lapis Lazuli", "opaque light and dark blue with yellow flecks", DefaultValues.gp10),
            new StandardItem("Malachite", "opaque striated light and dark green)", DefaultValues.gp10),
            new StandardItem("Moss Agate", "translucent pink or yellow-white with mossy gray or green markings", DefaultValues.gp10),
            new StandardItem("Obsidian", "opaque black", DefaultValues.gp10),
            new StandardItem("Rhodochrosite", "opaque light pink", DefaultValues.gp10),
            new StandardItem("Tiger Eye", "translucent brown with golden center", DefaultValues.gp10),
            new StandardItem("Turquoise", "opaque light blue-green", DefaultValues.gp10),
            new StandardItem("Bloodstone", "opaque dark gray with red flecks", DefaultValues.gp50),
            new StandardItem("Carnelian", "opaque orange to red-brown", DefaultValues.gp50),
            new StandardItem("Chalcedony", "opaque white", DefaultValues.gp50),
            new StandardItem("Chrysoprase", "translucent green", DefaultValues.gp50),
            new StandardItem("Citrine", "transparent pale yellow-brown", DefaultValues.gp50),
            new StandardItem("Jasper", "opaque blue, black, or brown", DefaultValues.gp50),
            new StandardItem("Moonstone", "translucent white with pale blue glow", DefaultValues.gp50),
            new StandardItem("Onyx", "opaque bands of black and white, or pure black or white", DefaultValues.gp50),
            new StandardItem("Quartz", "transparent white, smoky gray, or yellow", DefaultValues.gp50),
            new StandardItem("Sardonyx", "opaque bands of red and white", DefaultValues.gp50),
            new StandardItem("Star rose quartz", "translucent rosy stone with white star-shaped center", DefaultValues.gp50),
            new StandardItem("Zircon", "transparent pale blue-green", DefaultValues.gp50),
            new StandardItem("Amber", "transparent watery gold to rich gold", DefaultValues.gp100),
            new StandardItem("Amethyst", "transparent deep purple", DefaultValues.gp100),
            new StandardItem("Chrysoberyl", "transparent yellow-green to pale green", DefaultValues.gp100),
            new StandardItem("Coral", "opaque crimson", DefaultValues.gp100),
            new StandardItem("Garnet", "transparent red, brown-green, or violet", DefaultValues.gp100),
            new StandardItem("Jade", "translucent light green, deep green, or white", DefaultValues.gp100),
            new StandardItem("Jet", "opaque deep black", DefaultValues.gp100),
            new StandardItem("Pearl", "opaque lustrous white, yellow, or pink", DefaultValues.gp100),
            new StandardItem("Spinel", "transparent red, red-brown, or deep green", DefaultValues.gp100),
            new StandardItem("Tourmaline", "transparent pale green, blue, brown, or red", DefaultValues.gp100),
            new StandardItem("Alexandrite", "transparent dark green", DefaultValues.gp500),
            new StandardItem("Aquamarine", "transparent pale blue-green", DefaultValues.gp500),
            new StandardItem("Black Pearl", "opaque pure black", DefaultValues.gp500),
            new StandardItem("Blue Spinel", "transparent deep blue", DefaultValues.gp500),
            new StandardItem("Peridot", "transparent rich olive green", DefaultValues.gp500),
            new StandardItem("Topaz", "transparent golden yellow", DefaultValues.gp500),
            new StandardItem("Black Opal", "translucent dark green with black mottling and golden flecks", DefaultValues.gp1000),
            new StandardItem("Blue Sapphire", "transparent blue-white to medium blue", DefaultValues.gp1000),
            new StandardItem("Emerald", "transparent deep bright green", DefaultValues.gp1000),
            new StandardItem("Fire Opal", "translucent fiery red", DefaultValues.gp1000),
            new StandardItem("Opal", "translucent pale blue with green and golden mottling", DefaultValues.gp1000),
            new StandardItem("Star Ruby", "translucent ruby with white star-shaped center", DefaultValues.gp1000),
            new StandardItem("Star Sapphire", "translucent blue sapphire with white star-shaped center", DefaultValues.gp1000),
            new StandardItem("Yellow Sapphire", "transparent fiery yellow or yellow-green", DefaultValues.gp1000),
            new StandardItem("Black Sapphire", "translucent lustrous black with glowing highlights", DefaultValues.gp5000),
            new StandardItem("Diamond", "transparent blue-white, canary, pink, brown, or blue", DefaultValues.gp5000),
            new StandardItem("Jacinth", "transparent fiery orange", DefaultValues.gp5000),
            new StandardItem("Ruby", "transparent clear red to deep crimson", DefaultValues.gp5000)
        };
    }
}
